// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"fiber-admin/internal/pkg/config"
	"fiber-admin/internal/pkg/dao"
	"fiber-admin/internal/pkg/dao/mods"
	"fiber-admin/internal/pkg/service"
	"fiber-admin/internal/pkg/service/admin"
	mods2 "fiber-admin/internal/pkg/service/admin/mods"
	"fiber-admin/internal/pkg/service/common"
	mods3 "fiber-admin/internal/pkg/service/common/mods"
	"fiber-admin/internal/pkg/service/sys"
	mods4 "fiber-admin/internal/pkg/service/sys/mods"
	"fiber-admin/pkg/jwt"
	"fiber-admin/pkg/mongo"
	"fiber-admin/pkg/prometheus"
	"fiber-admin/pkg/redis"
	"fiber-admin/pkg/zap"
	"fiber-admin/test/mock"
	"github.com/casbin/casbin/v2"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeTestInjector(ctx context.Context, config2 *config.Config, n int) (*Injector, error) {
	redis, err := InitializeRedis(ctx, config2)
	if err != nil {
		return nil, err
	}
	cache := dao.NewCache(redis, config2)
	mongo, err := InitializeMongo(ctx, config2)
	if err != nil {
		return nil, err
	}
	zap, err := InitializeZap(config2)
	if err != nil {
		return nil, err
	}
	jwt, err := InitializeJwt(config2)
	if err != nil {
		return nil, err
	}
	prometheus := InitializePrometheus(config2)
	core, err := dao.NewCore(ctx, mongo, zap, config2)
	if err != nil {
		return nil, err
	}
	userDao, err := mods.NewUserDao(ctx, core, cache)
	if err != nil {
		return nil, err
	}
	noticeDao, err := mods.NewNoticeDao(ctx, core, cache)
	if err != nil {
		return nil, err
	}
	documentationDao, err := mods.NewDocumentationDao(ctx, core, cache)
	if err != nil {
		return nil, err
	}
	loginLogDao, err := mods.NewLoginLogDao(ctx, core, cache, userDao)
	if err != nil {
		return nil, err
	}
	operationLogDao, err := mods.NewOperationLogDao(ctx, core, cache, userDao)
	if err != nil {
		return nil, err
	}
	userDaoMock := mock.NewUserDaoMockWithRandomData(n, userDao)
	noticeDaoMock := mock.NewNoticeDaoMockWithRandomData(n, noticeDao)
	documentationDaoMock := mock.NewDocumentationDaoMockWithRandomData(n, documentationDao)
	loginLogDaoMock := mock.NewLoginLogDaoMockWithRandomData(n, loginLogDao, userDaoMock)
	operationLogDaoMock := mock.NewOperationLogDaoMockWithRandomData(n, operationLogDao, userDaoMock, noticeDaoMock, documentationDaoMock)
	serviceCore, err := service.NewCore(ctx, config2, zap)
	if err != nil {
		return nil, err
	}
	documentationService := mods2.NewDocumentationService(serviceCore, documentationDao)
	noticeService := mods2.NewNoticeService(serviceCore, noticeDao)
	logsService := mods2.NewLogsService(serviceCore, loginLogDao, operationLogDao)
	enforcer, err := InitializeCasbinEnforcer(config2)
	if err != nil {
		return nil, err
	}
	userService := mods2.NewUserService(serviceCore, userDao, enforcer)
	authService := mods3.NewAuthService(serviceCore, userDao, cache, jwt)
	idempotencyService := mods3.NewIdempotencyService(serviceCore, cache)
	modsDocumentationService := mods3.NewDocumentationService(serviceCore, documentationDao)
	modsNoticeService := mods3.NewNoticeService(serviceCore, noticeDao)
	profileService := mods3.NewProfileService(serviceCore, userDao)
	modsLogsService := mods4.NewLogsService(serviceCore, loginLogDao, operationLogDao)
	wireInjector := &Injector{
		Ctx:                        ctx,
		Config:                     config2,
		Cache:                      cache,
		Mongo:                      mongo,
		Redis:                      redis,
		Zap:                        zap,
		Jwt:                        jwt,
		Prometheus:                 prometheus,
		UserDao:                    userDao,
		NoticeDao:                  noticeDao,
		DocumentationDao:           documentationDao,
		LoginLogDao:                loginLogDao,
		OperationLogDao:            operationLogDao,
		UserDaoMock:                userDaoMock,
		NoticeDaoMock:              noticeDaoMock,
		DocumentationDaoMock:       documentationDaoMock,
		LoginLogDaoMock:            loginLogDaoMock,
		OperationLogDaoMock:        operationLogDaoMock,
		AdminDocumentationService:  documentationService,
		AdminNoticeService:         noticeService,
		AdminLogsService:           logsService,
		AdminUserService:           userService,
		CommonAuthService:          authService,
		CommonIdempotencyService:   idempotencyService,
		CommonDocumentationService: modsDocumentationService,
		CommonNoticeService:        modsNoticeService,
		CommonProfileService:       profileService,
		SysLogsService:             modsLogsService,
		Enforcer:                   enforcer,
	}
	return wireInjector, nil
}

// wire.go:

type Injector struct {
	// Common
	Ctx        context.Context
	Config     *config.Config
	Cache      *dao.Cache
	Mongo      *mongo.Mongo
	Redis      *redis.Redis
	Zap        *zap.Zap
	Jwt        *jwt.Jwt
	Prometheus *prometheus.Prometheus

	// DAOs
	UserDao          mods.UserDao
	NoticeDao        mods.NoticeDao
	DocumentationDao mods.DocumentationDao
	LoginLogDao      mods.LoginLogDao
	OperationLogDao  mods.OperationLogDao

	// Mocks for DAOs
	UserDaoMock          *mock.UserDaoMock
	NoticeDaoMock        *mock.NoticeDaoMock
	DocumentationDaoMock *mock.DocumentationDaoMock
	LoginLogDaoMock      *mock.LoginLogDaoMock
	OperationLogDaoMock  *mock.OperationLogDaoMock

	// Services
	// Admin services
	AdminDocumentationService mods2.DocumentationService
	AdminNoticeService        mods2.NoticeService
	AdminLogsService          mods2.LogsService
	AdminUserService          mods2.UserService
	// Common services
	CommonAuthService          mods3.AuthService
	CommonIdempotencyService   mods3.IdempotencyService
	CommonDocumentationService mods3.DocumentationService
	CommonNoticeService        mods3.NoticeService
	CommonProfileService       mods3.ProfileService
	// Sys services
	SysLogsService mods4.LogsService

	// Casbin enforcer
	Enforcer *casbin.Enforcer
}

var (
	ServiceProviderSet = wire.NewSet(service.NewCore, wire.Struct(new(admin.Admin), "*"), wire.Struct(new(common.Common), "*"), wire.Struct(new(sys.Sys), "*"), mods2.NewUserService, mods2.NewNoticeService, mods2.NewDocumentationService, mods2.NewLogsService, mods3.NewAuthService, mods3.NewProfileService, mods3.NewDocumentationService, mods3.NewNoticeService, mods3.NewIdempotencyService, mods4.NewLogsService)

	DaoProviderSet = wire.NewSet(dao.NewCore, dao.NewCache, mods.NewUserDao, mods.NewNoticeDao, mods.NewLoginLogDao, mods.NewOperationLogDao, mods.NewDocumentationDao)

	MockProviderSet = wire.NewSet(mock.NewUserDaoMockWithRandomData, mock.NewNoticeDaoMockWithRandomData, mock.NewLoginLogDaoMockWithRandomData, mock.NewOperationLogDaoMockWithRandomData, mock.NewDocumentationDaoMockWithRandomData)
)
